### ISSUE TITLE
Actions fails to resolve & doesn't exist in the marketplace 

### ISSUE THREAD

**Issue by jdesulme** [ActionsDesk/enterprise-members-report-action#83]
I setup an action to try this out and it can't find this action. Looking in the marketplace it doesn't even show up either. https://github.com/marketplace?type=actions&query=ghec-enterprise+

```
Failed to resolve action download info. Error: Unable to resolve action `ActionsDesk/enterprise-members-report-action@latest`, unable to find version `latest`
Retrying in 13.335 seconds
Failed to resolve action download info. Error: Unable to resolve action `ActionsDesk/enterprise-members-report-action@latest`, unable to find version `latest`
Retrying in 18.533 seconds
Error: Unable to resolve action `ActionsDesk/enterprise-members-report-action@latest`, unable to find version `latest`
```

**Comment by droidpl** [comment]
@jdesulme This action is indeed not published in the marketplace. However you can still use it straight away from the repository. The problem is that you are trying to reference a tag that doesn't exist called `@latest`. Pick one of the released versions and replace `latest` with that version to start using it.
